### PR TITLE
Update maya TankFileManager to add opened files into recent file list.

### PR DESCRIPTION
**Pull request by foutoucour**
Update maya TankFileManager to add opened files into recent file list.

### CODE REVIEW

**Comment by mfe** [comment]
I would have made the pep8 modifs in a separate commit but LGTM.

**Comment by kookiCT** [comment]
Where's the "Approve" button ?

**Comment by foutoucour** [comment]
@mfe It will be done the way you suggest in the future. This way it will be easier to apply only the pep8, you are right.

@kookiCT there is none :p . To approve or decline a PR on github, the usage wants to put :+1:  or :-1: as the first thing in the message. The system counts the point. As on bitbucket we have the rule of 2 approvals to merge, we need 2 :+1: to set a PR as approved I guess. Would you agree?

**Comment by mfe** [comment]
:+1:

**Comment by foutoucour** [comment]
Well it seems I overestimated github... it doesn't count the +1 (thx @mfe for the detail)
We will need to count the score ourselves. But no worry, I got a calc on my smartphone :)

**Comment by kookiCT** [comment]
:+1:

**Pull request merged**
